// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/.well-known/wallets.ts";
import * as $1 from "./routes/.well-known/wallets/[symbol].ts";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/music.tsx";
import * as $6 from "./routes/projects.tsx";

const manifest = {
  routes: {
    "./routes/.well-known/wallets.ts": $0,
    "./routes/.well-known/wallets/[symbol].ts": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/music.tsx": $5,
    "./routes/projects.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
